services:
  database-server:
    container_name: database-server
    image: mysql
    environment:
      - MYSQL_DATABASE=seoul-tennis
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
