spring:
  application:
    name: tennis-reservation
  profiles:
    default: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tennis-reservation
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  type-aliases-package: com.jnlim.tennis
  configuration:
    map-underscore-to-camel-case: true

open:
  api:
    seoul:
      url: http://openAPI.seoul.go.kr:8088
      key: ${SEOUL_REST_API_KEY}
      type: json
      service: ListPublicReservationSport
    kakao:
      url: https://dapi.kakao.com
      key: ${KAKAO_REST_API_KEY}

logging:
  level:
    org.springframework.cache: trace

springdoc:
  swagger-ui:
    path: /tennis-api
    groups-order: desc
    tags-sorter: alpha
    operations-sorter: method
  paths-to-match: /tennis/**
